name: Build and deploy
on: [push, repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install --force
        npm ci
        npm run build
    - name: Upload public dir
      uses: actions/upload-artifact@v4
      with:
        name: public
        path: public
      env:
        CI: true
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download public dir
      uses: actions/download-artifact@v4
      with:
        name: public
    - name: Upload ftp
      uses: havok89/ftp-action@releases/v3
      with:
        host: ${{ secrets.ftp_host }}
        user: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        localDir: "public"
